version: "3.9"

services:
  emi:
    build: .
    image: ${TAG}:${TAG}
    container_name: ${TAG}
    network_mode: host
    pull_policy: never

networks:
  default: 
    external: true
    name: host